### ISSUE TITLE
Replace current Character implementation with State design pattern

### ISSUE THREAD

**Issue by mtyski** [LazyBallsZealots/dnd-ddd#15]
1. Implement State design pattern, replacing existing inheriting types: ```ICharacterState``` should validate all operations available on both ```CompletedCharacter``` and ```CharacterDraft``` (throw domain exceptions where necessary, i.e.: changing AbilityScores once Character is completed);
2. Modify existing NHibernate mapping by removing table-per-class hierarchy mapping and introducing newly created property ```CharacterState``` (it should be internal with private setter).
3. Introduce new ```IUserType``` implementation, similar to existing ```RaceType```.

DOD:
 - all existing specifications pass;
 - pull request accepted by all reviewers;
 - merge completed successfully.

**Comment by ntiany** [comment]
ICharacterState was replaced with abstract class

**Comment by mtyski** [comment]
Pull request merged, closing issue
